### ISSUE TITLE
Support for gradient in color

### ISSUE THREAD

**Issue by f1010** [xqwzts/flutter_sparkline#1]
Is there a way to provide gradient in Fill mode?

**Comment by xqwzts** [comment]
It is now!

I've added `lineGradient` and `fillGradient` options which accept a [Gradient](https://docs.flutter.io/flutter/painting/Gradient-class.html) object and use it as a shader for the line or fill paint.

Take a look at the examples in the Readme to get started.

**Comment by xqwzts** [comment]
Closed by #2

**Comment by f1010** [comment]
oh, nice. But I have done that already by modifying your library. Also, adding a support for beizer curve will be nicer. I have already done that. - will send you the PR. Thanks.

**Comment by xqwzts** [comment]
PRs would be most welcome :)
