### ISSUE TITLE
Unable to install on flutter dev channel project

### ISSUE THREAD

**Issue by Abhith** [xqwzts/flutter_sparkline#6]
> flutter_sparkline >=0.0.2 which requires SDK version >=1.19.0 <2.0.0, version solving failed.

flutter doctor -v
[√] Flutter (Channel dev, v0.7.5, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 0.7.5 
    • Framework revision eab5cd9853 (2 days ago), 2018-08-30 14:47:04 -0700
    • Engine revision dc7b5eb89d
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

**Comment by andersonhonorio** [comment]
You need to chang  'environment' in pubspec.yaml test and request a PR.
I can do this.
